{{- if .Values.serviceAccounts.sparkoperator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  annotations:
    "helm.sh/hook": pre-install
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
