{{- if .Values.serviceAccounts.spark.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.sparkJobNamespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
